version: '3.7'

services:
  lft-graphql-db:
    image: "postgres"
    container_name: 'ltf-postgres-db'
    restart: 'no'
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    env_file:
      - database.env

