spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ltf?useSSL=false
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dilect: org.hibernate.dialect.MySQL5Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <google client id>
            clientSecret: <google oauth2 client secret>
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - profile
          facebook:
            clientId: facebook_app_id
            clientSecret: facebook_app_secret
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

server:
    port: 5000

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  enabled: true
  cdn:
    enabled: true
