spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ltf_database?useSSL=false
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dilect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 5000

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  enabled: true
  cdn:
    enabled: true
