spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ltf-graphql-db?useSSL=false
    username: ltf-graphql-user
    password: ltf-graphql-pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dilect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 5000

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  enabled: true
  cdn:
    enabled: true
