spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lft-graphql-db?useSSL=false
    username: lft-graphql-user
    password: lft-graphql-pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dilect: org.hibernate.dialect.MySQL5Dialect

server:
    port: 5000
